### ISSUE TITLE
My findings

### ISSUE THREAD

**Issue by fabicodes** [nv1t/standing-desk-interceptor#11]
Hello,
first of all many thanks for your work so far. I came across your repository by accident, after I got stuck with the height decoding myself.
I have an EK2 table from Flexispot. I haven't decoded the buttons yet, but I'm pretty confident that they are identical to yours.
For the heights, I assume that they are stored in the control unit itself, but that's just a guess.
To record the data I currently have a solution of a RJ45 splitter and a Saleae Logic Analyzer Clone.
Later I want to use an ESP8266 to do the communication with it. I can then also integrate this via MQTT into my home assistant.

Have you made any progress so far, or have you let the project rest since then?

Here is some data that I have found out so far:

Messages between the Controller and the Panel:
```
MSG Control Panel: 	9B 06 02 00 00 6C A1 9D
RESP Motor Control:	9B 04 15 BF C2 9D		9B 04 11 7C C3 9D

MSG Control Panel: 	9B 06 02 00 00 6C A1 9D
RESP Motor Control:	9B 04 15 BF C2 9D		9B 07 12 7F FD 4F 04 A4 9D		9B 04 11 7C C3 9D
```

Some more height data:
```
86.3	9b 07 12 7f fd 4f 04 a4 9d
87.0	9b 07 12 7f 87 3f 80 86 9d
87.3	9b 07 12 7f 87 4f 64 87 9d
87.9	9b 07 12 7f 87 6f bc 86 9d
88.0	9b 07 12 7f ff 3f 80 a4 9d
88.3	9b 07 12 7f ff 4f 64 a5 9d
88.8	9b 07 12 7f ff 7f 70 a5 9d
89.0	9b 07 12 7f ef 3f 40 a9 9d
89.1	9b 07 12 7f ef 06 52 69 9d
89.2	9b 07 12 7f ef 5b ab a8 9d
89.3	9b 07 12 7f ef 4f a4 a8 9d
89.4	9b 07 12 7f ef 66 7a 69 9d
89.5	9b 07 12 7f ef 6d bd 28 9d
89.6	9b 07 12 7f ef 7d 71 29 9d
89.7	9b 07 12 7f ef 07 92 a8 9d
89.8	9b 07 12 7f ef 7f b0 a8 9d
89.9	9b 07 12 7f ef 6f 7c a9 9d
90.0	9b 07 12 6f bf 3f 85 94 9d
90.1	9b 07 12 6f bf 06 97 54 9d
90.2	9b 07 12 6f bf 5b 6e 95 9d
90.3	9b 07 12 6f bf 4f 61 95 9d
```

My current recording setup:
![My current setup](https://user-images.githubusercontent.com/1745612/103791852-3eb4cf80-5043-11eb-8806-cb1a590ad5b4.jpg)
My control panel:
![My Control Panel](https://user-images.githubusercontent.com/1745612/103791862-3fe5fc80-5043-11eb-9828-16e1db469785.jpg)
[The manual of my desk](https://de.flexispot.com/media/productattach/e/k/ek2_montageanleitung_1.pdf)

**Comment by nv1t** [comment]
Hi Fabicodes, 
Sorry for the reaaally late answer. I have a raspberry pi as intercepting proxy between the motorcontroller and the controlpanel. It is a serial connection, therefore i dropped the logic analyzer from my setup. 

I am not sure about the heights. I think i was able to replay a button without the controlpanel attached. That would mean the height is encoded in the command itself. Because the Button commands are fixed, the height has to be stored on the motor controler side.

I haven't looked into the data since the project rested, because i didn't have any time working on it. The project was on hold for quite a while, because of the intercepting proxy...i wanted to build something more stable to use with other projects....and this took quite some time :) 

Feel free to push/merge, work on it :) happy not to be alone on this one.

**Comment by nv1t** [comment]
ok...i had a look around. somebody worked on it. it is in german, but explains it really really good: https://www.mikrocontroller.net/topic/493524

**Comment by nv1t** [comment]
I have added the height the encoding of the height to the readme file in front.

**Comment by fabicodes** [comment]
> ok...i had a look around. somebody worked on it. it is in german, but explains it really really good: https://www.mikrocontroller.net/topic/493524

Whoa, this is an awesome finding! Thank you very much :)

**Comment by iMicknl** [comment]
@fabicodes I was wondering if you were able to capture the 'wake up' command to receive the current height. I wrote a ESPHome implementation for Home Assistant, but I only receive the new height when I execute a command like presets / up / down. (or if I wake up the desk controller screen by touching it).

Do you perhaps know if the PIN20 needs to be high/low when you execute the wake up command?

I have the same desk and I am currently using Home Assistant to pull the statistics + to control it via voice.

**Comment by fabicodes** [comment]
@iMicknl Unfortunately my control panel reacts as immediately as you press a key with the action that the key should perform. Therefore, I doubt that I will find a wake-up command in my control panel variant. But I noticed yesterday by accident at my girlfriend that her controlpanel only wakes up when a key is pressed and displays the height.
I will have a closer look at this soon(™, probably after the exam period) with the Logic Analyzer.
Thanks for the ESP-Home implementation, by the way, that was also on my ToDo list.

Her panel looks like this: 
![image](https://user-images.githubusercontent.com/1745612/112815581-c1688c00-9080-11eb-917a-f21795159134.png)
(Source: https://de.flexispot.com/elektrisch-hohenverstellbares-gestell-eq5.html)

**Comment by iMicknl** [comment]
> @iMicknl Unfortunately my control panel reacts as immediately as you press a key with the action that the key should perform. Therefore, I doubt that I will find a wake-up command in my control panel variant. But I noticed yesterday by accident at my girlfriend that her controlpanel only wakes up when a key is pressed and displays the height.

I feel stupid since I have the same control panel 👀, but indeed you are right. 

The 'wake up' command implemented in the [ESPHome implementation](https://github.com/iMicknl/LoctekMotion_IoT/tree/main/packages/esphome) is perhaps already working for the desk of your girlfriend. I would be interested to learn more about above control panel and pinouts by the way, feel free to do a [PR](https://github.com/iMicknl/LoctekMotion_IoT) if you know more.

Good luck with your exams!
